### ISSUE TITLE
Runtime Error: Can't Read Property 'From'

### ISSUE THREAD

**Issue by SiS-Wireless** [tobyallen/email2sms#2]
Hi,

Tried using your script per [this doc](https://www.twilio.com/blog/two-way-email-to-sms-sendgrid-twilio) but I'm getting the following error whenever I try to send a text message from my phone to the twilio phone #. I've tried working w/ Twilio & Sendgrid support but I'm not getting anywhere. Can you help?

Here is the error log I see in vercel.com dashboard whenever I try to send a test txt message from my phone to the twilio phone #:

`[POST] /api/sms2email
2021-04-28T22:22:08.535Z	10fd37db-3634-496e-a8b6-d8ddf0a857f2	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'From' of undefined","reason":{"errorType":"TypeError","errorMessage":"Cannot read property 'From' of undefined","stack":["TypeError: Cannot read property 'From' of undefined","    at module.exports (/var/task/api/sms2email.js:8:34)","    at Server.<anonymous> (/var/task/___vc_helpers.js:813:19)","    at Server.emit (events.js:315:20)","    at parserOnIncoming (_http_server.js:874:12)","    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'From' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}Unknown application error occurred`

And here is the URL to the hosted scripts:

https://twilio-email-2-sms-fzl2xckut-sis-wirelesssolu.vercel.app/api/index

Thank you for any assistance you can provide.

SW

**Comment by tobyallen** [comment]
Hi SW, thanks for reaching out. Can you confirm that you have all the environment variables setup correctly and that you're hitting this function with the "When a Message comes in ..." webhook setup from Twilio console?

**Comment by SiS-Wireless** [comment]
Hi tobyallen,

Thank you for your assistance. Not sure what you mean by "have all the environment variables setup correctly". Do I need to edit the github scripts manually? I used the "Quick Deploy" of the [doc I followed](https://www.twilio.com/blog/two-way-email-to-sms-sendgrid-twilio) which didn't mention any changes needed to be done w/ the github scripts manually.

Here is what I have in Twilio:
![image](https://user-images.githubusercontent.com/83234740/116551095-8ea2f500-a8c5-11eb-94cf-f027d05579b2.png)

Here is what I have in vercel which has the github clone of your script:
![image](https://user-images.githubusercontent.com/83234740/116551397-e5a8ca00-a8c5-11eb-8b7a-5f3c40f42a95.png)

And here is what I have in Sendgrid:
![image](https://user-images.githubusercontent.com/83234740/116552932-982d5c80-a8c7-11eb-9069-c37cc45e1970.png)

Thank you again for your assistance!

SW
